<?PHP
#
#   FILE:  Chart.php
#
#   Part of the Metavus digital collections platform
#   Copyright 2017-2025 Edward Almasy and Internet Scout Research Group
#   http://metavus.net
#
# @scout:phpstan

namespace Metavus;
use Exception;
use InvalidArgumentException;
use ScoutLib\ApplicationFramework;

/**
 * Base class for generating and displaying a chart.
 */
abstract class Chart
{
    # ---- PUBLIC INTERFACE --------------------------------------------------

    /**
     * Get/set data for chart.
     * @param array $NewValue Data in format specified by chart type. (OPTIONAL)
     * @return array Current data.
     */
    public function data(?array $NewValue = null): array
    {
        if ($NewValue !== null) {
            $this->Data = $NewValue;
        }
        return $this->Data;
    }

    /**
     * Set legend position.
     * @param string $Position Legend position as a BarChart::LEGEND_
     *         constant. LEGEND_BOTTOM (the default) will place the legend
     *         below the chart, LEGEND_RIGHT will place it at the right, and
     *         LEGEND_NONE will disable the legend entirely.
     * @throws Exception If an invalid legend position is supplied.
     */
    public function setLegendPosition(string $Position): void
    {
        if (!in_array($Position, [
            self::LEGEND_BOTTOM,
            self::LEGEND_RIGHT,
            self::LEGEND_NONE
        ])) {
            throw new Exception("Unsupported legend position: ".$Position);
        }
        $this->LegendPosition = $Position;
    }

    /**
     * Set shortened labels to be used in the legend of the chart.
     * @param array $LegendLabels Array of legend labels to use, with keys
     *         matching the keys of the data passed to the constructor. Any
     *         labels that do not need shortening may be omitted.
     */
    public function setLegendLabels(array $LegendLabels): void
    {
        $this->LegendLabels = $LegendLabels;
    }

    /**
     * Get/set chart element labels (pie slices, bars, etc).
     * @param array|boolean $NewValue Label strings for chart, indexed by the
     *         same values used to index chart data, or FALSE to clear any
     *         existing labels. (OPTIONAL)
     * @return array|boolean $Labels Label strings for chart, indexed by the
     *         same values used to index chart data, or FALSE if no labels
     *         have been set.
     * @throws InvalidArgumentException If invalid type of new value supplied.
    */
    public function labels($NewValue = null)
    {
        if ($NewValue !== null) {
            if (!is_array($NewValue) && ($NewValue !== false)) {
                throw new InvalidArgumentException("Invalid new value (".$NewValue.").");
            }
            $this->Labels = $NewValue;
        }
        return $this->Labels;
    }

    /**
     * Get/set color palette. Bars with no color defined will use an
     *         autogenerated color.
     * @param array|false $NewValue Array of hex colors (e.g., '#1f77b4'),
     *         indexed by the keys used in the constructor, or false to clear
     *         any existing color palette. (OPTIONAL)
     * @return array|false Current color palette, or false if no color palette set.
     */
    public function colors($NewValue = null)
    {
        if ($NewValue !== null) {
            $this->Colors = $NewValue;
        }
        return $this->Colors;
    }

    /**
     * Get/Set height of the chart including the legend. If not set
     * explicitly, defaults to 600 px.
     * @param int $NewValue New height in pixels (OPTIONAL).
     * @return int Current height in pixels.
     */
    public function height(?int $NewValue = null): int
    {
        if ($NewValue !== null) {
            $this->Height = $NewValue;
        }
        return $this->Height;
    }

    /**
     * Get/Set width of the chart including the legend. If not set explicitly,
     *         defaults to 600 px.
     * @param int $NewValue New width in pixels (OPTIONAL).
     * @return int Current width in pixels.
     */
    public function width(?int $NewValue = null): int
    {
        if ($NewValue !== null) {
            $this->Width = $NewValue;
        }
        return $this->Width;
    }

    /**
     * Turn on automatic sizing of the chart based on the width of the
     * containing element. When enabled, the height of the chart will be
     * computed based on the aspect ratio of the width() and height() of the
     * chart.
     */
    public function makeAutosizing(): void
    {
        $this->Autosize = true;
    }

    /**
     * Display a chart. Thee charts are generated with Plotly, which outputs
     *         SVGs that can be styled with CSS. In practice, it's often
     *         simplest to use your browser's "Inspect Element" feature to
     *         locate SVG elements and the classes they use to customize them.
     * @param string $ContainerId Id to use when generating the div to contain this chart.
     * @see https://plotly.com/javascript/
     * @see https://developer.mozilla.org/en-US/docs/Web/SVG/Element
     */
    public function display(string $ContainerId): void
    {
        self::requireNeededFiles();
        $CssClass = "mv-chart";
        if ($this->Autosize) {
            $CssClass .= " mv-chart-autosize";
        }
        $AspectRatio = $this->Width / $this->Height;
        ?>
        <div id="<?= $ContainerId ?>" class="<?= $CssClass ?>"
             data-aspect="<?= $AspectRatio ?>"></div>
        <script>
        (function(){
            var ContainerId = '<?= $ContainerId ?>';
            var Plot = Plotly.newPlot(
                ContainerId,
                <?= json_encode($this->getChartData()) ?>,
                <?= json_encode($this->getChartLayout()) ?>,
                <?= json_encode($this->getChartConfig()) ?>
            );
            <?= static::getPostChartJS() ?>
        })();
        </script>
        <?PHP
    }

    /**
     * Set up the chart environment so that cached HTML (e.g., in a DataCache)
     *         from a previous display() call will function
     *         properly. Application code that implements an HTML cache will
     *         need to call this for cache hits.
     */
    public static function prepForDisplayingCachedVersion(): void
    {
        self::requireNeededFiles();
    }

    # legend position constants
    const LEGEND_BOTTOM = "bottom";
    const LEGEND_RIGHT = "right";
    const LEGEND_NONE = "none";

    # ---- PRIVATE INTERFACE --------------------------------------------------

    /**
     * Include necessary JS for chart generation.
     */
    protected static function requireNeededFiles(): void
    {
        $AF = ApplicationFramework::getInstance();
        $AF->requireUIFile("plotly.js", ApplicationFramework::ORDER_FIRST);
        $AF->requireUIFile("Chart.js", ApplicationFramework::ORDER_FIRST);
        $AF->requireUIFile("Chart.css");
    }

    /**
     * Get data in the format required by Plotly for the 'data' argument to
     *         Plotly.newPlot().
     * @see https://plotly.com/javascript/plotlyjs-function-reference/#plotlynewplot
     */
    abstract protected function getChartData(): array;

    /**
     * Get chart layout information in the format required for the 'layout'
     *         argument to Plotly.newPlot().
     * @see https://plotly.com/javascript/plotlyjs-function-reference/#plotlynewplot
     * @see https://plotly.com/javascript/reference/layout/
     */
    protected function getChartLayout(): array
    {
        $Layout = [];
        $Layout["height"] = $this->Height;
        $Layout["width"] = $this->Width;

        switch ($this->LegendPosition) {
            case self::LEGEND_BOTTOM:
                $Layout["legend"]["orientation"] = "h";
                break;

            case self::LEGEND_RIGHT:
                $Layout["legend"]["orientation"] = "v";
                $Layout["legend"]["yanchor"] = "middle";
                $Layout["legend"]["y"] = "0.5";
                break;

            case self::LEGEND_NONE:
                $Layout["legend"]["visible"] = false;
                break;

            default:
                throw new Exception(
                    "Unknown Legend Position - should be impossible."
                );
        }

        return $Layout;
    }

    /**
     * Get chart configuration information in the format required for the
     *         'config' argument to Plotly.newPlot().
     * @see https://plotly.com/javascript/plotlyjs-function-reference/#plotlynewplot
     * @see https://plotly.com/javascript/configuration-options/
     */
    protected function getChartConfig(): array
    {
        $Config["displayModeBar"] = false;
        $Config["responsive"] = true;
        $Config["paper_bgcolor"] = "transparent";
        $Config["doubleClickDelay"] = 600; # in ms (default was 300)

        return $Config;
    }

    /**
     * Get JS that should be printed after the chart, without an enclosing
     *         <script> tags. Will be included inside an IIFE containing a
     *         'Plot' variable holding the result of Plotly.newPlot().
     */
    protected function getPostChartJS(): string
    {
        return "";
    }

    /**
     * Get RGB hex color when no color supplied.
     * @param string $DataIndex Index for data for which color will be used.
     * @return string RGB hex color string.
     */
    protected function generateRgbColorString($DataIndex): string
    {
        return "#".substr(md5($DataIndex), 0, 6);
    }

    # data provided by caller
    protected $Data = [];

    # chart parameters that can be changed prior to generation
    protected $LegendPosition = self::LEGEND_BOTTOM;
    protected $Colors = false;
    protected $Labels = [];
    protected $LegendLabels = [];
    protected $Height = 600;
    protected $Width = 600;
    protected $Autosize = false;
}
