<?PHP
#
#   FILE: MultiDateChart.php
#
#   Part of the Metavus digital collections platform
#   Copyright 2018-2025 Edward Almasy and Internet Scout Research Group
#   http://metavus.net
#
# @scout:phpstan

namespace Metavus;
use Exception;

/**
 * Class for generating and displaying a trio of day/month/year date
 * charts inside a tabbed comtainer.
 */
class MultiDateChart
{

    # ---- PUBLIC INTERFACE --------------------------------------------------

    /**
     * Create new MultiDateChart and initialize default values.
     */
    public function __construct()
    {
        foreach ($this->ChartTypes as $ChartType) {
            $this->Charts[$ChartType] = new BarChart();
            $this->Charts[$ChartType]->axisType(
                constant("Metavus\\BarChart::AXIS_TIME_".strtoupper($ChartType))
            );
            $this->Charts[$ChartType]->autoscale(true);
            $this->Charts[$ChartType]->showSubchart(true);
        }
    }

    /**
     * Display the HTML for this multi-date chart.
     * @param string $IdPrefix HTML Id prefix for this chart, which
     *     must be unique on the page where it is displayed.
     */
    public function display(string $IdPrefix) : void
    {
        $TabUI = new TabbedContentUI();

        foreach ($this->ChartTypes as $ChartType) {
            $TabUI->beginTab($ChartType);
            $this->Charts[$ChartType]->display($IdPrefix."_".$ChartType);
        }

        $TabUI->display($IdPrefix."_Tabs");
    }

    /**
     * Enable/Disable automatic scaling after zooming for this chart.
     * @param bool $NewValue TRUE to enable autoscale, or FALSE to disable.
     */
    public function autoscale(bool $NewValue): void
    {
        $this->forwardCall(__FUNCTION__, [$NewValue]);
    }

    /**
     * Set bar width as a percentage of the distance between ticks.
     * @param int $NewValue Updated bar width.
     * @throws Exception If an invalid bar width is supplied.
     */
    public function barWidth(int $NewValue): void
    {
        $this->forwardCall(__FUNCTION__, [$NewValue]);
    }

    /**
     * Set color palette. Bars with no color defined will use an
     *         autogenerated color.
     * @param array|false $NewValue Array of hex colors (e.g., '#1f77b4'),
     *         indexed by the keys used in the constructor, or false to clear
     *         any existing color palette
     */
    public function colors($NewValue): void
    {
        $this->forwardCall(__FUNCTION__, [$NewValue]);
    }

    /**
     * Set data for chart.
     * @param array $NewValue Data for chart. Keys are X values for each bar
     *   (unix timestamp, sor any format that strtotime can parse). Values are
     *   ints for charts with only one set of bars or associative arrays where
     *   the keys give bar names and the values give bar heights for charts
     *   with multiple bars.
     */
    public function data($NewValue = null): void
    {
        $this->forwardCall(__FUNCTION__, [$NewValue]);
    }

    /**
     * Set height of the chart including the legend. If not set
     * explicitly, defaults to 600 px.
     * @param int $NewValue New height in pixels
     */
    public function height(int $NewValue): void
    {
        $this->forwardCall(__FUNCTION__, [$NewValue]);
    }

    /**
     * Set width of the chart including the legend. If not set explicitly,
     * defaults to 600 px.
     * @param int $NewValue New width in pixels.
     */
    public function width(int $NewValue): void
    {
        $this->forwardCall(__FUNCTION__, [$NewValue]);
    }


    /**
     * Set legend position.
     * @param string $NewValue Legend position as a BarChart::LEGEND_
     *         constant. LEGEND_BOTTOM (the default) will place the legend
     *         below the chart, LEGEND_RIGHT will place it at the right, and
     *         LEGEND_NONE will disable the legend entirely.
     * @throws Exception If an invalid legend position is supplied.
     */
    public function setLegendPosition(string $NewValue): void
    {
        $this->forwardCall(__FUNCTION__, [$NewValue]);
    }

    /**
     * Set shortened labels to be used in the legend of the chart.
     * @param array $NewValue Array of legend labels to use, with keys
     *         matching the keys of the data passed to the constructor. Any
     *         labels that do not need shortening may be omitted.
     */
    public function setLegendLabels($NewValue): void
    {
        $this->forwardCall(__FUNCTION__, [$NewValue]);
    }

    /**
     * Set bar labels
     * @param array|boolean $NewValue Label strings for chart, indexed by the
     *         same values used to index chart data, or FALSE to clear any
     *         existing labels.
     * @throws \InvalidArgumentException If invalid type of new value supplied.
    */
    public function labels($NewValue): void
    {
        $this->forwardCall(__FUNCTION__, [$NewValue]);
    }

    /**
     * Enable/Disable the subchart (a small chart below the main chart showing
     *         the full range of the x-axis that displays the currently zoomed
     *         portion of the data; disabled by default when this method has
     *         not been called).
     * @param bool $NewValue TRUE to enable subchart, or FALSE to disable.
     */
    public function showSubchart(bool $NewValue): void
    {
        $this->forwardCall(__FUNCTION__, [$NewValue]);
    }

    /**
     * Set bar stacking setting.
     * @param bool $NewValue TRUE to generate a stacked chart.
     */
    public function stacked(bool $NewValue): void
    {
        $this->forwardCall(__FUNCTION__, [$NewValue]);
    }

    /**
     * Enable/Disable zooming for this chart.
     * @param bool $NewValue TRUE to enable zooming, or FALSE to disable.
     */
    public function zoom(bool $NewValue): void
    {
        $this->forwardCall(__FUNCTION__, [$NewValue]);
    }

    /**
     * Turn on automatic sizing of the chart based on the width of the
     * containing element. When enabled, the height of the chart will be
     * computed based on the aspect ratio of the width() and height() of the
     * chart.
     */
    public function makeAutosizing(): void
    {
        $this->forwardCall(__FUNCTION__, []);
    }

    # ---- PRIVATE INTERFACE -------------------------------------------------

    /**
     * Forward calls to BarChart setters to the Daily/Weekly/Monthly
     *         bar charts contained in this MultiDateChart.
     * @param string $Function Function that was called.
     * @param array $Args Function arguments.
     * @return void
     */
    private function forwardCall(string $Function, array $Args): void
    {
        # call the delegated function on each chart
        foreach ($this->ChartTypes as $ChartType) {
            if (!$this->Charts[$ChartType] instanceof BarChart) {
                throw new Exception(
                    "SubChart ".$ChartType." is not a Metavus\\BarChart"
                        ." (should be impossible)."
                );
            }

            $Callable = [$this->Charts[$ChartType], $Function];
            if (!is_callable($Callable)) {
                throw new Exception(
                    "Call to invalid function ".$Function
                );
            }

            call_user_func_array($Callable, $Args);
        }
    }


    private $Charts = [];
    private $ChartTypes = ["Daily", "Weekly", "Monthly"];
}
